const $=s=>document.querySelector(s);const app=$('#app');
const icon={home:'⌂',astro:'✦',planet:'◉',calendar:'◷',research:'⌬',lab:'⚗',tool:'⌘'};
const groups={
  'Core Astrology':['Kundli','Kundli Matching','Lagna','Navamsa D9','Bhava Chart','Rashi Chart','Nakshatra','Pada','Dasha','Antardasha','Yogas','Doshas','Ashtakavarga','Shadbala','Vimshottari','Yogini Dasha','Jaimini','KP Astrology','Tajika','Prashna'],
  'Panchang & Muhurta':['Panchang','Tithi','Vara','Nakshatra Day','Yoga Day','Karana','Rahu Kalam','Gulika Kalam','Yamaganda','Choghadiya','Abhijit Muhurta','Muhurta Finder','Festival Calendar','Ekadashi','Amavasya','Purnima'],
  'Graha Intelligence':['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn','Rahu','Ketu','Planet Strength','Transit','Retrograde','Combustion','Conjunctions','Aspects','Graha Gochar'],
  'Astronomy':['Solar System','Planetary Positions','Moon Phases','Solar Eclipses','Lunar Eclipses','Rise & Set','Sidereal Time','Julian Date','Coordinate Converter','Angular Separation','Orbit Calculator','Kepler Solver','N-Body Concepts','Small Bodies','Asteroids','Comets','NEO Watch','Exoplanets'],
  'Astrophysics Lab':['Stellar Physics','Stellar Evolution','Black Holes','Neutron Stars','Gravitational Waves','Relativity','Cosmology','Space Weather','Solar Wind','CMEs','Energetic Particles','Habitability','Atmospheric Escape','Magnetospheres','Radiation Environment','Exoplanet Climate'],
  'Research & AI':['Research Papers','Paper Explorer','Evidence Graph','Scientific Claims','AI Astronomer','AI Vedic Analyst','Model Router','Research Copilot','Explain Calculation','Citation Trace','Uncertainty Lab','Hypothesis Lab'],
  'Tools & Life':['Daily Sky','Today','Tomorrow','Year Planner','Life Planner','Decision Lab','Learning Path','Science Lessons','Observation Planner','Journal','Saved Reports','Settings']
};
const allPages=Object.entries(groups).flatMap(([g,ps])=>ps.map(p=>({group:g,name:p,id:p.toLowerCase().replace(/[^a-z0-9]+/g,'-')})));
let state={screen:'splash',slide:0,page:'home'};
function boot(){setTimeout(()=>{state.screen='onboarding';render()},1500)}
const slides=[
 {ey:'ASTROSUN / SCIENCE FIRST',t:'Know the sky. Understand the system.',p:'A research-grade astronomy + astrology workspace. Planetary positions are computed from explicit models, evidence is cited, uncertainty is visible, and traditional astrology is kept separate from physical causation.',tag:'ASTRONOMY + ASTROLOGY'},
 {ey:'EPHEMERIS ENGINE',t:'From a birth time to a real sky model.',p:'Julian dates, orbital periods, Kepler solving, sidereal transformations and configurable ephemeris adapters form the calculation layer. Production mode can be connected to JPL/NASA data.',tag:'PRECISION CALCULATION'},
 {ey:'RESEARCH GRAPH',t:'Every strong claim gets a source trail.',p:'Research-paper cards, claim confidence, citation traces and a scientific/interpretive split keep the experience logical instead of pretending astrology is experimentally established physics.',tag:'EVIDENCE LAYER'},
 {ey:'AI ROUTER',t:'Two providers. One seamless brain.',p:'NVIDIA NIM and AIHubMix are connected server-side. If the primary provider fails, the router can automatically fail over to the second configured provider without exposing keys to the browser.',tag:'NVIDIA NIM + AIHUBMIX'}
];
function render(){if(state.screen==='splash'){app.innerHTML=`<div class="splash"><div class="stars"></div><div class="splash-card"><div class="logo-orbit"></div><h1>AstroSun</h1><p>Cosmic Intelligence • Research • Life</p><div class="loader"><span></span></div><small>initializing scientific engine</small></div></div>`;boot();return}if(state.screen==='onboarding'){const s=slides[state.slide];app.innerHTML=`<div class="onboarding"><div class="slide"><div class="slide-copy"><div class="eyebrow">${s.ey}</div><h2>${s.t}</h2><p>${s.p}</p><span class="badge">${s.tag}</span><div class="onboard-actions">${state.slide<3?`<button class="btn ghost" onclick="nextSlide()">Next</button>`:`<button class="btn orange" onclick="enterApp()">Enter AstroSun</button>`}</div><div class="dots">${slides.map((_,i)=>`<span class="dot ${i===state.slide?'on':''}"></span>`).join('')}</div></div><div class="slide-visual"><div class="orbit"></div><div class="planet"></div></div></div></div>`;return}renderApp()}
window.nextSlide=()=>{state.slide=Math.min(3,state.slide+1);render()};window.enterApp=()=>{state.screen='app';render()};
function navButton(p){return `<button class="nav-item ${state.page===p.id?'active':''}" onclick="go('${p.id}')"><span>${icon[p.group==='Astronomy'?'planet':p.group==='Astrophysics Lab'?'research':p.group==='Research & AI'?'lab':p.group==='Tools & Life'?'tool':'astro']||'•'}</span>${p.name}</button>`}
function renderApp(){const page=allPages.find(x=>x.id===state.page);app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark"></div><strong>AstroSun</strong></div>${Object.entries(groups).map(([g,ps])=>`<div class="nav-group"><div class="nav-label">${g}</div>${ps.slice(0, g==='Core Astrology'?10:8).map(n=>navButton(allPages.find(x=>x.name===n))).join('')}</div>`).join('')}</aside><main class="main"><div class="topbar"><input class="search" placeholder="Search 100+ cosmic tools…" onkeydown="if(event.key==='Enter')search(this.value)"><div class="status">● scientific engine online</div></div><div class="content">${page?featurePage(page):dashboard()}</div></main><nav class="bottomnav">${[['home','Home'],['Kundli','Kundli'],['Panchang','Panchang'],['Solar System','Sky'],['AI Astronomer','AI']].map(([n,l])=>{const p=n==='home'?{id:'home'}:allPages.find(x=>x.name===n);return `<button class="${state.page===p.id?'active':''}" onclick="go('${p.id}')">${l}</button>`}).join('')}</nav></div>`}
window.go=id=>{state.page=id;render()};window.search=q=>{const hit=allPages.find(p=>p.name.toLowerCase().includes(q.toLowerCase()));if(hit){state.page=hit.id;render()}};
function dashboard(){return `<section class="hero"><span class="badge">ASTROSUN RESEARCH BUILD</span><h1>One sky. Many layers of truth.</h1><p>Calculate the sky first. Interpret tradition second. Explain evidence and uncertainty every time. AstroSun combines an astronomy engine, a Vedic astrology layer, research papers and an AI routing layer into one colorful workspace.</p><div class="toolbar"><button class="btn orange" onclick="go('kundli')">Create Kundli</button><button class="btn ghost" onclick="go('solar-system')">Open Sky Model</button><button class="btn ghost" onclick="go('research-papers')">Research Library</button></div></section><div class="grid"><div class="card"><div class="metric">120+</div><h3>Feature pages</h3><p>Data-driven route system across astrology, panchang, astronomy, astrophysics and AI.</p></div><div class="card"><div class="metric">2×</div><h3>AI failover</h3><p>NVIDIA NIM primary + AIHubMix fallback through a server-side router.</p></div><div class="card"><div class="metric">JPL</div><h3>Ephemeris-ready</h3><p>Adapter architecture for NASA/JPL-grade observations and ephemerides.</p></div><div class="card"><div class="metric">∞</div><h3>Evidence graph</h3><p>Separate measured physics from interpretive astrology claims.</p></div></div><h2 class="section-title">Launch pads</h2><div class="grid">${['Kundli','Panchang','Planetary Positions','Orbit Calculator','Space Weather','Exoplanets','Research Papers','AI Astronomer'].map(n=>{const p=allPages.find(x=>x.name===n);return `<div class="card" onclick="go('${p.id}')"><h3>${n}</h3><p>Open the ${n.toLowerCase()} workspace →</p></div>`}).join('')}</div><p class="disclaimer">Scientific boundary: planetary positions, orbital mechanics, stellar physics and space weather are scientific domains. Traditional astrology is presented as a cultural/interpretive system; the app does not claim that planetary positions cause personality, health or life outcomes.</p>`}
function featurePage(p){const scientific=['Astronomy','Astrophysics Lab'].includes(p.group);const calc=calcDemo(p.name);return `<div class="feature-page"><section class="hero"><span class="badge">${p.group.toUpperCase()}</span><h1>${p.name}</h1><p>${description(p.name)}</p><div class="toolbar"><button class="btn orange" onclick="runAI('${p.name}')">Ask AstroSun AI</button><button class="btn ghost" onclick="go('explain-calculation')">Explain calculation</button><button class="btn ghost" onclick="go('research-papers')">Show evidence</button></div></section>${calc}<section class="ai-box" id="ai-${p.id}"><strong>AI analysis</strong><p>Ask the dual-provider research assistant to explain this module, cite the relevant paper set and distinguish measured facts from interpretive statements.</p></section></div>`}
function description(n){const map={Kundli:'Generate a birth-chart workspace using date, time and place. Astronomy supplies the sky geometry; the interpretation layer remains explicitly separate.',Panchang:'Day-level timekeeping: tithi, vara, nakshatra, yoga and karana with sunrise/sunset adapters and configurable location.', 'Planetary Positions':'Compute geocentric or heliocentric positions, apparent motion, retrograde intervals and coordinate transforms.', 'Orbit Calculator':'Solve Kepler’s equation and estimate orbital state, period, velocity, escape velocity and transfer quantities.', 'Space Weather':'Inspect solar-wind, flare, CME and energetic-particle concepts with an evidence-first model.', 'Research Papers':'Explore papers behind the calculation engine, including modern ephemeris and stellar-forcing research.', 'AI Astronomer':'Ask the routed research model to explain a calculation, compare hypotheses or generate a cited research brief.'};return map[n]||`A dedicated AstroSun module for ${n.toLowerCase()}, combining deterministic calculations, data adapters, visualizations and an AI explanation layer.`}
function calcDemo(n){if(n==='Julian Date')return `<div class="card"><h3>Julian Date</h3><div class="toolbar"><input id="jd-date" class="input" type="datetime-local"><button class="btn orange" onclick="calcJD()">Calculate</button></div><p id="jd-out" class="metric">—</p></div>`;if(n==='Orbit Calculator')return `<div class="card"><h3>Kepler solver</h3><div class="toolbar"><input id="a" class="input" value="1" placeholder="a (AU)"><input id="e" class="input" value="0.0167" placeholder="e"><input id="M" class="input" value="0" placeholder="M°"><button class="btn orange" onclick="orbitCalc()">Solve</button></div><p id="orbit-out">Enter semi-major axis, eccentricity and mean anomaly.</p></div>`;if(n==='Angular Separation')return `<div class="card"><h3>Angular separation</h3><p>Great-circle separation from two RA/Dec points.</p><div class="toolbar"><input id="ra1" class="input" placeholder="RA₁°"><input id="dec1" class="input" placeholder="Dec₁°"><input id="ra2" class="input" placeholder="RA₂°"><input id="dec2" class="input" placeholder="Dec₂°"><button class="btn orange" onclick="angSep()">Calculate</button></div><p id="ang-out" class="metric">—</p></div>`;if(scientificPage(n))return `<div class="grid"><div class="card"><h3>Model status</h3><div class="metric">READY</div><p>Deterministic layer active. External ephemeris/data providers can be attached without changing the UI.</p></div><div class="card"><h3>Uncertainty</h3><div class="metric">VISIBLE</div><p>Every estimate can carry source, epoch, model and confidence metadata.</p></div><div class="card"><h3>Research basis</h3><div class="metric">PAPERS</div><p>Ephemeris and stellar-forcing literature is linked to this layer.</p></div><div class="card"><h3>AI role</h3><div class="metric">EXPLAIN</div><p>AI explains outputs; it does not replace the deterministic calculation.</p></div></div>`;return `<div class="card"><h3>Interactive workspace</h3><p>Inputs, calculation cards, evidence and AI explanation panels are reserved for this module. This foundation keeps the 100+ page system consistent and fast.</p></div>`}
function scientificPage(n){return ['Solar System','Planetary Positions','Moon Phases','Solar Eclipses','Lunar Eclipses','Rise & Set','Sidereal Time','Coordinate Converter','N-Body Concepts','Small Bodies','Asteroids','Comets','NEO Watch','Exoplanets','Stellar Physics','Stellar Evolution','Black Holes','Neutron Stars','Gravitational Waves','Relativity','Cosmology','Space Weather','Solar Wind','CMEs','Energetic Particles','Habitability','Atmospheric Escape','Magnetospheres','Radiation Environment','Exoplanet Climate'].includes(n)}
window.calcJD=()=>{const v=$('#jd-date').value;if(!v)return;const d=new Date(v+'Z');const jd=d.getTime()/86400000+2440587.5;$('#jd-out').textContent=jd.toFixed(8)};
window.orbitCalc=()=>{const a=Number($('#a').value),e=Number($('#e').value),M=Number($('#M').value)*Math.PI/180;let E=M;for(let i=0;i<20;i++)E-=((E-e*Math.sin(E)-M)/(1-e*Math.cos(E)));const r=a*(1-e*Math.cos(E));const n=0.01720209895/Math.pow(a,1.5);$('#orbit-out').innerHTML=`E = <b>${(E*180/Math.PI).toFixed(5)}°</b> · r = <b>${r.toFixed(6)} AU</b> · mean motion ≈ <b>${(n*180/Math.PI).toFixed(6)}°/day</b>`};
window.angSep=()=>{const r=x=>Number($(x).value)*Math.PI/180;const a1=r('#ra1'),d1=r('#dec1'),a2=r('#ra2'),d2=r('#dec2');const c=Math.min(1,Math.max(-1,Math.sin(d1)*Math.sin(d2)+Math.cos(d1)*Math.cos(d2)*Math.cos(a1-a2)));$('#ang-out').textContent=(Math.acos(c)*180/Math.PI).toFixed(6)+'°'};
window.runAI=async name=>{const el=$(`#ai-${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`);if(!el)return;el.innerHTML='<strong>AI analysis</strong><p>Routing request…</p>';try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:'nvidia',fallback:true,messages:[{role:'system',content:'You are AstroSun Research Copilot. Be scientifically rigorous. Separate measured astronomy/astrophysics from traditional astrology. Never present astrology as experimentally validated causation. Give concise citations or named research areas when known.'},{role:'user',content:`Explain the AstroSun module “${name}”. Give calculation logic, useful inputs, uncertainty, and how it should be used in life without making unsupported causal claims.`}]})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI unavailable');el.innerHTML=`<strong>AI analysis · ${d.provider}</strong><p>${escapeHtml(d.text).replace(/\n/g,'<br>')}</p>`}catch(e){el.innerHTML=`<strong>AI analysis unavailable</strong><p>${escapeHtml(e.message)}</p><p class="disclaimer">Configure NVIDIA_NIM_API_KEY + NVIDIA_NIM_MODEL and optionally AIHUBMIX_API_KEY + AIHUBMIX_MODEL on Render. The browser never receives these keys.</p>`}};
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
render();
